### ISSUE TITLE
Use Cloc to count number of comment lines, blank lines and pure code.

### ISSUE THREAD

**Issue by michaeldoubek** [the-simian/es6-plato#46]
It would be nice to see in the first chart data from CLOC (https://github.com/kentcdodds/cloc) in a chart similar to http://www.chartjs.org/samples/latest/charts/area/line-stacked.html

**Comment by the-simian** [comment]
Oh hey this is an awesome idea! Thank you for the suggestion!!

I will do my best to carve out some time to work on this, I think its very valuable feedback for sure.

**Comment by michaeldoubek** [comment]
I have some other ideas but it would take some time, so I will make a fork and will try to add some features when I have time. Thanks for implementing this!

**Comment by the-simian** [comment]
hey thanks again for the feature request. To be honest i've been fantasizing about completely rewriting this project to make a lot of enhancements myself. time is hard to come by :)

I'm gonna close this, since IDK if there's anything actionable for me here. If you make some changes by all means I will 100% pull it in if its working

Thank you again!!
