### ISSUE TITLE
Renaming the repo

### ISSUE THREAD

**Issue by Asuza** [the-simian/es6-plato#55]
I realize the name you gave it makes perfect sense, but have you considered renaming it to Aristotle, since that's the name of Plato's best student?

You mentioned in an issue somewhere that you were able to simplify the original Plato code while updating it for ES6, so it seems fitting to me.

**Comment by the-simian** [comment]
All this is true, however I have kept it as this name because I felt like at some point I may very well merge this into the plato master branch, but the merge conflicts were great, and it was not as easy as it looked at the time.

I've also considered starting over on this project and building the interface in something like React, which is what I work in usually these days. Ultimately if I did that, I'd pick a new name, a new repo, and direct users of this project to that.

I'm closing the issue, because I've read it and thought about it. I sincerely appreciate you opening this and sharing your thoughts. I'd say watch this repo, I might very well just rework this platform someday and make the tool I've always wanted. es6-plato is awesome, but I think it can do much more.
