### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by alex-pollan** [the-simian/es6-plato#69]
It seems that there is an issue with some missing dependencies.

This is my environement:
- nodejs v8.11.4
- npm v6.4.1

I do this:

```
npm install --save-dev es6-plato
npm run complexity-report
```
I get this error: _Failed to load plugin import: Cannot find module 'eslint-plugin-import'_
I install the missing module and try again:
```
npm install --save-dev eslint-plugin-import
npm run complexity-report
```

then I get: _Cannot find module 'babel-eslint'_
I install the missing module and try again:
```
npm install --save-dev babel-eslint
npm run complexity-report
```
then it worked

😕 Could it be ``npm install`` ignoring vulnerable dependencies? I see audit errors after installing but I didn't dig into them

**Comment by the-simian** [comment]
Just to cover our bases did you add this to your scripts in package.json?
`"complexity-report": "./node_modules/.bin/es6-plato -r -d ./report src"`
@alex-pollan

**Comment by alex-pollan** [comment]
yes, I did it to be able to do : ``npm run complexity-report``

**Comment by the-simian** [comment]
@alex-pollan I am not sure about ti skipping, at least I don't think so because none of those dependencies are that far behind, but to be honest its probably time to update them anyways just to be on the safe side. I am using this in a lot of my own day-to-day projects and I haven't seen this error, but I might be just suppressing it with stale modules too.

let me try this on a new project, see what happens.

**Comment by the-simian** [comment]
@alex-pollanI think this is about grunt-casper. I'm removing that, so that will fix this. Grunt-Capser is super out of date and also now considered a vuln dep

the removal of that should clear this up.

**Comment by the-simian** [comment]
This is gone in 1.1.6
